version: '3'
services:
  backend:
    build:
      context: ./BACKEND
    ports:
      - "5000:5000"
    depends_on:
      - frontend
      - mongo-bdd
      - redis-bdd

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:3000"

  mongo-bdd:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis-bdd:
    image: redis:latest
    ports:
      - "6379:6379"
